### ISSUE TITLE
clicking 'Create' button on firefox results in "a.webkitCreateShadowRoot is undefined"

### ISSUE THREAD

**Issue by mlamberson** [vsavkin/angulardart-sample-app#1]
Firefox 25.0 (Mozilla Firefox for Ubuntu canonical - 1.0)

[06:51:06.912] "NullError: a.webkitCreateShadowRoot is undefined        

STACKTRACE:
.cv.er@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:41473
J.Rx@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:71116
.Z4.call$6@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:5252
.Gf.call$1@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:5140
.Ek@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:2633
.on.jT@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:57378
J.Zz@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:71187
.LR.call$0@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:57286
.yU@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:57420
.Ua.kp@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:57477
.cX.xD@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:57201
.cX.ox@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:57224
J.Xk@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:71171
.uHO.call$1@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:5180
.bQ@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:13431
.Q.aN@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:1117
J.kH@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:71268
.ll.lK@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:5030
.ll.lw@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4976
.ll.lw@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4977
.ll.lw@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4977
.ll.lw@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4977
.ll.call$2@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4951
.ll.call$1@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4955
.Kw.call$1@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:9946
.vs.GP@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16670
.jb.call$0@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16907
.T8@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16000
.Id.Vn@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19521
.AP.call$0@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4730
.G3.YF@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4663
.G3.Cwz@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4672
$$.QdT<.call$4@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:211
.Id.Vn@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19521
.uo.Gr@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19722
.vs.static.HZ@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16834
.vs.rX@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16740
.rH.call$0@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16880
.T8@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16000
.Id.Vn@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19521
.pu.call$0@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4744
.T8@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:16003
.Id.Vn@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19521
.G3.n1@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4693
.G3.YF@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4670
.G3.O0p@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:4676
$$.RTS<.call$5@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:214
.Id.qG@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19528
.uo.FI@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19726
.fZ.m1@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19610
.Cg.call$1@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:19663
.TL.call$0@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:3379
.aX.vV@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:1953
.zd@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:1796
.ft@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:2709
.tR/z</<@http://vsavkin.github.io/angulardart-sample-app/talk_to_me.dart.js:2718
"

**Comment by mlamberson** [comment]
Looking into this, i suspect it's probably similar to this dart2js bug:

http://code.google.com/p/dart/issues/detail?id=15144

**Comment by sethladd** [comment]
This is still an issue. Confirmed.

**Comment by sethladd** [comment]
In fact, for me, I can't get the app to even start in Firefox :)

**Comment by vsavkin** [comment]
Fixed by https://github.com/vsavkin/angulardart-sample-app/pull/7
