### ISSUE TITLE
Update app to work with AngularDart v1.0

### ISSUE THREAD

**Issue by poffe** [vsavkin/angulardart-sample-app#22]
Hi!

First of all, thanks for a great example of how to implement something using AngularDart.

Could anyone, if needed, update it so it works with AngularDart v1.0? (Or maybe point me to some other example app using AngularDart v1.0)

Cheers!

**Comment by vsavkin** [comment]
Fixed via https://github.com/vsavkin/angulardart-sample-app/pull/23
